Repository CrunchyData/pgmonitor, pull requests merged in 2020-01, with the labels that each got.

#151 Reverting CODEOWNERS back to individual team members
  CODEOWNERS
Labels: bug

#126 Add PostgreSQL 12 support
  exporter/postgres/crunchy-postgres-exporter-pg12-el6.service
  exporter/postgres/queries_pg12.yml
  exporter/postgres/setup_pg12.sql
  exporter/postgres/sysconfig.postgres_exporter_pg12
  exporter/postgres/sysconfig.postgres_exporter_pg12_per_db
  hugo/content/_index.md
  hugo/content/changelog/_index.md
Labels: enhancement

#150 Remove unused job cleanup scripts
  prometheus/remove-job-data-2.0.sh
  prometheus/remove-job-data.sh
Labels: enhancement

#148 Use label_values() to populate template variables
  grafana/Bloat_Details.json
  grafana/CRUD_Details.json
  grafana/Filesystem_Details.json
  grafana/OS_Details.json
  grafana/OS_Details.json.win
  grafana/OS_Overview.json
  grafana/OS_Overview.json.win
  grafana/PGBackrest.json
  grafana/PGBouncer.json
  grafana/PG_Details.json
  grafana/PG_Overview.json
  grafana/TableSize_Details.json
Labels: bug

#158 move content to .github and update templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: TYPE: FEATURE
